var EntityLogicalName = "contact";
var Form_1fed44d1_ae68_4a41_bd2b_f13acac4acfa_Properties = {
accountrolecode: "accountrolecode"
,company: "company"
,emailaddress1: "emailaddress1"
,fullname: "fullname"
,mobilephone: "mobilephone"
,ownerid: "ownerid"
,td_companyname: "td_companyname"
,td_contacttype: "td_contacttype"
,td_locationsponsororcro: "td_locationsponsororcro"
,td_prefix: "td_prefix"
,td_suffix: "td_suffix"
,td_surveycountry: "td_surveycountry"
,td_surveyinstituteaddress1: "td_surveyinstituteaddress1"
,td_surveyinstituteaddress2: "td_surveyinstituteaddress2"
,td_surveyinstitutecity: "td_surveyinstitutecity"
,td_surveyinstitutefax: "td_surveyinstitutefax"
,td_surveyinstitutename: "td_surveyinstitutename"
,td_surveyinstitutephone: "td_surveyinstitutephone"
,td_surveyinstitutepostalcode: "td_surveyinstitutepostalcode"
,td_surveyinstitutestate: "td_surveyinstitutestate"
,td_surveyregion: "td_surveyregion"
,td_surveyta: "td_surveyta"
};

var Form_1fed44d1_ae68_4a41_bd2b_f13acac4acfa_Controls = {
accountrolecode: "accountrolecode"
,company: "company"
,emailaddress1: "emailaddress1"
,fullname: "fullname"
,header_ownerid: "header_ownerid"
,mobilephone: "mobilephone"
,notescontrol: "notescontrol"
,td_companyname: "td_companyname"
,td_contacttype: "td_contacttype"
,td_locationsponsororcro: "td_locationsponsororcro"
,td_prefix: "td_prefix"
,td_suffix: "td_suffix"
,td_surveycountry: "td_surveycountry"
,td_surveyinstituteaddress1: "td_surveyinstituteaddress1"
,td_surveyinstituteaddress2: "td_surveyinstituteaddress2"
,td_surveyinstitutecity: "td_surveyinstitutecity"
,td_surveyinstitutefax: "td_surveyinstitutefax"
,td_surveyinstitutename: "td_surveyinstitutename"
,td_surveyinstitutephone: "td_surveyinstitutephone"
,td_surveyinstitutepostalcode: "td_surveyinstitutepostalcode"
,td_surveyinstitutestate: "td_surveyinstitutestate"
,td_surveyregion: "td_surveyregion"
,td_surveyta: "td_surveyta"
};

